language: python
python:
  - '3.6'
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
install:
  - pip install -r requirements.txt .
before_script:
  - docker-compose -f itests/docker/docker-compose.yml up --build -d
script:
    - sleep 10 && pytest
after_script:
  - docker-compose -f itests/docker/docker-compose.yml down
after_success:
  - codecov # submit coverage
